version: '2'
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DATABASE_PASSWORD=admin
      - DATABASE_USER=postgres
      - PGDATA=/var/lib/postgresql/data

  bankslip-app:
    image: bankslip-app:latest
    ports:
      - "8080:8080"
    environment:
      PROFILE: "docker"
      SERVER_PORT: "8080"
      DATABASESERVER_PORT: 5432